// lib/products.ts — AUTO-GENERATED by sync_supabase_to_products_ts.mjs
// Last sync: 2026-09-24T17:07:37.674Z
// Total: 681 products

export interface VolumeOption { label: string; price: string; rawPrice: number }
export interface MediaItem { url: string; type: 'image' | 'video' }

export interface Product {
  id: string
  name: string
  category: string
  type?: string
  price: string
  rawPrice: number
  description?: string
  image: string
  images?: string[]
  media?: MediaItem[]
  tag?: string
  contenance?: string
  volumes?: VolumeOption[]
  colors?: string[]
  color?: string
  colorImages?: Record<string, string>
  rating?: number
  reviewsCount?: number
}

export function extractContenance(p?: {
  name?: string
  description?: string
  type?: string
  contenance?: string
  volumes?: VolumeOption[]
} | null): string {
  if (!p) return ''
  if (p.contenance && p.contenance.trim()) return p.contenance.trim()

  // Si des variantes de volumes existent, renvoyer la liste séparée par des virgules
  const vols = extractVolumes(p)
  if (vols.length > 0) {
    return vols.map((v) => v.volume).join(', ')
  }

  // 1. Marqueur dans la description
  const markerMatch = (p.description || '').match(/\[Contenance:\s*([^\]]+)\]/i)
  if (markerMatch) return markerMatch[1].trim()

  // 2. Recherche dans le nom (ex: "50 ml", "100 ml", "30ml", "200 ml")
  const nameMatch = (p.name || '').match(/(\d+[\s]*(?:ml|g|cl|oz))\b/i)
  if (nameMatch) {
    return nameMatch[1].replace(/(\d+)\s*(ml|g|cl|oz)/i, '$1 $2').toLowerCase()
  }

  // 3. Recherche dans le type
  const typeMatch = (p.type || '').match(/(\d+[\s]*(?:ml|g|cl|oz))\b/i)
  if (typeMatch) {
    return typeMatch[1].replace(/(\d+)\s*(ml|g|cl|oz)/i, '$1 $2').toLowerCase()
  }

  // 4. Recherche dans la description
  const descMatch = (p.description || '').match(/(\d+[\s]*(?:ml|g|cl|oz))\b/i)
  if (descMatch) {
    return descMatch[1].replace(/(\d+)\s*(ml|g|cl|oz)/i, '$1 $2').toLowerCase()
  }

  return ''
}

export function getCleanDescription(desc: string = ''): string {
  return desc
    .replace(/<!--VOLUMES_JSON_START-->[\s\S]*?<!--VOLUMES_JSON_END-->/g, '')
    .replace(/<!--COLORS_JSON_START-->[\s\S]*?<!--COLORS_JSON_END-->/g, '')
    .replace(/<!--COLOR_IMAGES_JSON_START-->[\s\S]*?<!--COLOR_IMAGES_JSON_END-->/g, '')
    .replace(/\n*\[Contenance:[^\]]+\]/gi, '')
    .replace(/\n*\[(?:Couleurs?|Colors?):[^\]]+\]/gi, '')
    .replace(/\n*\[(?:ColorImages|CouleurImages)(?:JSON)?:\s*\{[\s\S]*?\}\]/gi, '')
    .replace(/\n*\[Volumes(?:JSON)?:\s*\[[\s\S]*?\]\]/gi, '')
    .replace(/\n*\[Volumes:[^\]]+\]/gi, '')
    .replace(/\n*\[VolumesJSON:[^\]]+\]/gi, '')
    .trim()
}

/**
 * Retourne la description nettoyée de toute syntaxe image pour affichage condensé (cartes, badges)
 */
export function stripImagesFromDescription(desc?: string): string {
  if (!desc) return ''
  return getCleanDescription(desc)
    .replace(/!\[(.*?)\]\(.*?\)/g, '')
    .replace(/<img[^>]*>/gi, '')
    .trim()
}

export const COMMON_COLORS: { name: string; hex: string }[] = [
  { name: 'Noir', hex: '#1c1c1c' },
  { name: 'Blanc', hex: '#ffffff' },
  { name: 'Doré / Or', hex: '#d4af37' },
  { name: 'Argent', hex: '#c0c0c0' },
  { name: 'Beige / Nude', hex: '#e8dcce' },
  { name: 'Rose Poudré', hex: '#f3c5c5' },
  { name: 'Rouge Écarlate', hex: '#b91c1c' },
  { name: 'Bordeaux', hex: '#7f1d1d' },
  { name: 'Bleu Nuit', hex: '#1e3a8a' },
  { name: 'Vert Émeraude', hex: '#065f46' },
  { name: 'Marron / Cuir', hex: '#78350f' },
  { name: 'Gris Anthracite', hex: '#4b5563' },
  { name: 'Bronze', hex: '#cd7f32' },
  { name: 'Terracotta', hex: '#c86446' },
]

export const COLOR_TRANSLATIONS_ES: Record<string, string> = {
  'noir': 'Negro',
  'blanc': 'Blanco',
  'doré': 'Dorado',
  'dore': 'Dorado',
  'doré / or': 'Dorado / Oro',
  'dore / or': 'Dorado / Oro',
  'or': 'Oro',
  'argent': 'Plateado / Plata',
  'argenté': 'Plateado',
  'argente': 'Plateado',
  'beige': 'Beige',
  'beige / nude': 'Beige / Nude',
  'nude': 'Nude',
  'rose': 'Rosa',
  'rose poudré': 'Rosa Empolvado',
  'rose poudre': 'Rosa Empolvado',
  'rouge': 'Rojo',
  'rouge écarlate': 'Rojo Escarlata',
  'rouge ecarlate': 'Rojo Escarlata',
  'bordeaux': 'Burdeos',
  'bleu': 'Azul',
  'bleu nuit': 'Azul Noche',
  'bleu marine': 'Azul Marino',
  'bleu ciel': 'Azul Cielo',
  'vert': 'Verde',
  'verte': 'Verde',
  'vert émeraude': 'Verde Esmeralda',
  'vert emeraude': 'Verde Esmeralda',
  'vert olive': 'Verde Oliva',
  'vert olive / kaki': 'Verde Oliva / Caqui',
  'kaki': 'Caqui',
  'marron': 'Marrón',
  'marron / cuir': 'Marrón / Cuero',
  'cuir': 'Cuero',
  'brun': 'Marrón',
  'brun chocolat': 'Marrón Chocolate',
  'gris': 'Gris',
  'gris anthracite': 'Gris Antracita',
  'gris perle': 'Gris Perla',
  'gris argent perle': 'Gris Plata Perla',
  'bronze': 'Bronce',
  'terracotta': 'Terracota',
  'ivoire': 'Marfil',
  'ecru': 'Blanco Roto / Crudo',
  'écru': 'Blanco Roto / Crudo',
  'beige clair / écru': 'Beige Claro / Crudo',
  'beige clair / ecru': 'Beige Claro / Crudo',
  'beige rosé / nude': 'Beige Rosado / Nude',
  'beige rose / nude': 'Beige Rosado / Nude',
  'noir titane': 'Negro Titanio',
  'jaune': 'Amarillo',
  'orange': 'Naranja',
  'violet': 'Violeta',
  'pourpre': 'Púrpura',
}

/**
 * Traduit automatiquement un nom de couleur français vers l'espagnol pour les visiteurs de la boutique.
 * Conserve les couleurs déjà rédigées en espagnol intactes.
 */
export function formatColorEs(colorName: string): string {
  if (!colorName) return ''
  const trimmed = colorName.trim()
  const lower = trimmed.toLowerCase()

  // 1. Correspondance directe dans le dictionnaire
  if (COLOR_TRANSLATIONS_ES[lower]) {
    return COLOR_TRANSLATIONS_ES[lower]
  }

  // 2. Nettoyage de préfixes (ex: emojis "🤎 Beige rosé / Nude")
  const cleanLower = lower.replace(/^[^a-z0-9à-ÿ]+/i, '').trim()
  if (COLOR_TRANSLATIONS_ES[cleanLower]) {
    return COLOR_TRANSLATIONS_ES[cleanLower]
  }

  // 3. Remplacements par mots-clés courants
  let translated = trimmed
  const wordReplacements: [RegExp, string][] = [
    [/\bnoir\b/gi, 'Negro'],
    [/\bblanc\b/gi, 'Blanco'],
    [/\bblanche\b/gi, 'Blanco'],
    [/\bdoré\b/gi, 'Dorado'],
    [/\bdore\b/gi, 'Dorado'],
    [/\bargent\b/gi, 'Plata'],
    [/\bargenté\b/gi, 'Plateado'],
    [/\brouge\b/gi, 'Rojo'],
    [/\bbleu\b/gi, 'Azul'],
    [/\bvert\b/gi, 'Verde'],
    [/\bverte\b/gi, 'Verde'],
    [/\bmarron\b/gi, 'Marrón'],
    [/\bcuir\b/gi, 'Cuero'],
    [/\bbrun\b/gi, 'Marrón'],
    [/\banthracite\b/gi, 'Antracita'],
    [/\bclair\b/gi, 'Claro'],
    [/\bfoncé\b/gi, 'Oscuro'],
    [/\bnuit\b/gi, 'Noche'],
    [/\bmarine\b/gi, 'Marino'],
    [/\bperle\b/gi, 'Perla'],
    [/\bémeraude\b/gi, 'Esmeralda'],
    [/\bécarlate\b/gi, 'Escarlata'],
    [/\bpoudré\b/gi, 'Empolvado'],
    [/\bpoudre\b/gi, 'Empolvado'],
    [/\bjaune\b/gi, 'Amarillo'],
    [/\borange\b/gi, 'Naranja'],
    [/\bviolet\b/gi, 'Violeta'],
    [/\bchocolat\b/gi, 'Chocolate'],
    [/\bivoire\b/gi, 'Marfil'],
    [/\bécru\b/gi, 'Crudo'],
    [/\becru\b/gi, 'Crudo'],
    [/\brosé\b/gi, 'Rosado'],
    [/\brose\b/gi, 'Rosa'],
  ]

  for (const [pattern, replacement] of wordReplacements) {
    if (pattern.test(translated)) {
      translated = translated.replace(pattern, replacement)
    }
  }

  // Première lettre en majuscule
  return translated.charAt(0).toUpperCase() + translated.slice(1)
}

export function getColorHex(colorName: string): string {
  if (!colorName) return '#cccccc'
  const trimmed = colorName.trim()
  if (/^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(trimmed)) return trimmed

  const hexMatch = trimmed.match(/#([0-9a-f]{6}|[0-9a-f]{3})\b/i)
  if (hexMatch) return hexMatch[0]

  const lower = trimmed.toLowerCase()
  for (const c of COMMON_COLORS) {
    if (lower === c.name.toLowerCase() || c.name.toLowerCase().includes(lower) || lower.includes(c.name.toLowerCase().split(' ')[0])) {
      return c.hex
    }
  }

  if (lower.includes('noir') || lower.includes('black') || lower.includes('negro')) return '#1c1c1c'
  if (lower.includes('blanc') || lower.includes('white') || lower.includes('blanco')) return '#ffffff'
  if (lower.includes('or') || lower.includes('gold') || lower.includes('dor') || lower.includes('dorado')) return '#d4af37'
  if (lower.includes('argent') || lower.includes('silver') || lower.includes('plata') || lower.includes('plateado')) return '#c0c0c0'
  if (lower.includes('rose') || lower.includes('pink') || lower.includes('rosa')) return '#f472b6'
  if (lower.includes('rouge') || lower.includes('red') || lower.includes('rojo')) return '#dc2626'
  if (lower.includes('bleu') || lower.includes('blue') || lower.includes('azul')) return '#2563eb'
  if (lower.includes('vert') || lower.includes('green') || lower.includes('verde')) return '#16a34a'
  if (lower.includes('beige') || lower.includes('nude') || lower.includes('creme') || lower.includes('crème') || lower.includes('crudo')) return '#e8dcce'
  if (lower.includes('marron') || lower.includes('marrón') || lower.includes('brown') || lower.includes('cuir') || lower.includes('cuero')) return '#78350f'
  if (lower.includes('gris') || lower.includes('grey') || lower.includes('gray')) return '#6b7280'
  if (lower.includes('violet') || lower.includes('purple') || lower.includes('morado')) return '#7c3aed'
  if (lower.includes('jaune') || lower.includes('yellow') || lower.includes('amarillo')) return '#facc15'
  if (lower.includes('orange') || lower.includes('naranja')) return '#ea580c'
  if (lower.includes('terracotta') || lower.includes('terracota')) return '#c86446'
  if (lower.includes('bordeaux') || lower.includes('burdeos')) return '#7f1d1d'
  if (lower.includes('bronze') || lower.includes('bronce')) return '#cd7f32'

  return '#b8c8a6'
}

export function extractColors(p?: {
  colors?: string[]
  color?: string
  description?: string
} | null): string[] {
  if (!p) return []
  if (p.colors && Array.isArray(p.colors) && p.colors.length > 0) {
    return p.colors.map((c) => String(c).trim()).filter(Boolean)
  }
  if (p.color && typeof p.color === 'string' && p.color.trim()) {
    return p.color.split(',').map((c) => c.trim()).filter(Boolean)
  }

  const commentMatch = (p.description || '').match(/<!--COLORS_JSON_START-->([\s\S]*?)<!--COLORS_JSON_END-->/)
  if (commentMatch) {
    try {
      const parsed = JSON.parse(commentMatch[1].trim())
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed.map((c: any) => String(c).trim()).filter(Boolean)
      }
    } catch {}
  }

  const markerMatch = (p.description || '').match(/\[(?:Couleurs?|Colors?):\s*([^\]]+)\]/i)
  if (markerMatch) {
    return markerMatch[1].split(',').map((c) => c.trim()).filter(Boolean)
  }

  return []
}

export function extractColorImages(p?: {
  colorImages?: Record<string, string>
  description?: string
  colors?: string[]
  images?: string[]
} | null): Record<string, string> {
  if (!p) return {}
  if (p.colorImages && typeof p.colorImages === 'object' && Object.keys(p.colorImages).length > 0) {
    return p.colorImages
  }

  const commentMatch = (p.description || '').match(/<!--COLOR_IMAGES_JSON_START-->([\s\S]*?)<!--COLOR_IMAGES_JSON_END-->/)
  if (commentMatch) {
    try {
      const parsed = JSON.parse(commentMatch[1].trim())
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed
      }
    } catch {}
  }

  const markerMatch = (p.description || '').match(/\[(?:ColorImages|CouleurImages)(?:JSON)?:\s*(\{[\s\S]*?\})\s*\]/i)
  if (markerMatch) {
    try {
      const parsed = JSON.parse(markerMatch[1].trim())
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed
      }
    } catch {}
  }

  return {}
}

export const CATEGORIES = [
  "Todos los productos",
  "HORNOS",
  "HORNO DE PIZZA",
  "Chimenea",
  "ESTUFA DE LEÑA",
  "ESTUFA DE PELLETS",
  "Colchones",
  "Mueble de baño",
  "Mueble TV",
  "Mobiliario & Decoración",
  "Cuadros y Láminas",
  "FRIGORIFIGO",
  "LAVADORA SECADORA",
  "ASPIRADORA DYSON",
  "Juego de interior",
  "Belleza & cabello",
  "Jardín & Exterior",
  "Novedades televisores",
  "Aire Libre & Glamping",
  "Alta Cosmética & Cuidado Facial",
  "Perfumes de Autor",
  "Cuidado Corporal & Spa",
  "Hogar & Confort",
  "Velas & Aromas",
  "Alta Cosmética"
]


export const PRODUCTS: Product[] = [];
